const LEDGER_NAME = 'test-ledger-1';
const PATIENT_TABLE_NAME = 'test_table';
const INSERT_INTO_TEST_TABLE = "INSERT INTO test_table ?"
const INSERT_INTO_PATIENTS_TABLE = "INSERT INTO PATIENTS ?"
exports.LEDGER_NAME = LEDGER_NAME;
exports.PATIENT_TABLE_NAME = PATIENT_TABLE_NAME;
exports.INSERT_INTO_TEST_TABLE = INSERT_INTO_TEST_TABLE;
exports.INSERT_INTO_PATIENTS_TABLE = INSERT_INTO_PATIENTS_TABLE;